package io.github.herrromich.batch.builder.fluenrt.orchestrator

interface FluentOrchestratorJobAndTaskInterfaceBuilder : FluentOrchestratorJobInterfaceBuilder, FluentOrchestratorTaskInterfaceBuilder
